pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - author=dependabot[bot]
  - check-success*=ci/hydra:vim-niri-nav-rs:*:aarch64-linux.bin
  - check-success*=ci/hydra:vim-niri-nav-rs:*:aarch64-linux.hydra-spec
  - check-success*=ci/hydra:vim-niri-nav-rs:*:aarch64-linux.mergify-check
  - check-success*=ci/hydra:vim-niri-nav-rs:*:aarch64-linux.pre-commit-check
  - check-success*=ci/hydra:vim-niri-nav-rs:*:aarch64-linux.vim-niri-nav-clippy
  - check-success*=ci/hydra:vim-niri-nav-rs:*:aarch64-linux.vim-niri-nav-fmt
  - check-success*=ci/hydra:vim-niri-nav-rs:*:aarch64-linux.vim-niri-nav-test
  - check-success*=ci/hydra:vim-niri-nav-rs:*:x86_64-linux.bin
  - check-success*=ci/hydra:vim-niri-nav-rs:*:x86_64-linux.hydra-spec
  - check-success*=ci/hydra:vim-niri-nav-rs:*:x86_64-linux.mergify-check
  - check-success*=ci/hydra:vim-niri-nav-rs:*:x86_64-linux.pre-commit-check
  - check-success*=ci/hydra:vim-niri-nav-rs:*:x86_64-linux.vim-niri-nav-clippy
  - check-success*=ci/hydra:vim-niri-nav-rs:*:x86_64-linux.vim-niri-nav-fmt
  - check-success*=ci/hydra:vim-niri-nav-rs:*:x86_64-linux.vim-niri-nav-test
  name: Automatically merge dependabot updates
